#!/usr/bin/env bash
set -e # halt script on error

# skip if build is triggered by pull request
if [ $TRAVIS_PULL_REQUEST == "true" ]; then
  echo "this is PR, exiting"
  exit 0
fi

# enable error reporting to the console
set -e

# cleanup "_site"
rm -rf _site
mkdir _site

# clone remote repo to "_site"
git clone https://${GITHUB_TOKEN}@github.com/GradyHooker/esportskingdom.git --branch gh-pages _site

# build with Jekyll into "_site"
bundle exec jekyll build

# copy cname file
cp CNAME _site

# create new images
mkdir _site/assets/logos/medium
mkdir _site/assets/logos/tiny
cd _site/assets/logos/original
mogrify -path _site/assets/logos/medium -resize 80x80 -format png *.png
mogrify -path _site/assets/logos/tiny -resize 24x24 -format png *.png
cd ../../../../

# push
echo "Pushing Site"
cd _site
git config user.name "Travis CI Bot"
git add --all
git commit -a -m "Travis #$TRAVIS_BUILD_NUMBER"
git push --force origin gh-pages
echo "Site Pushed"